name: "Report Tachometer Results"
description: "Report the results of Polymer/tachometer in a comment for PRs"
author: andrewiggins
branding:
  icon: bar-chart-2 # clipboard, file-text, flag, trending-up, upload
  color: purple
inputs:
  path:
    description: "The path to the results JSON file of running tachometer. Accepts a glob to report multiple result files. Follows rules of @actions/glob"
    required: false
  pr-num:
    description: "The number of the pull request to add a comment to containing the benchmark results"
    required: false
  report-id:
    description: "A string to uniquely identify this report between other instances of tachometer-reporter-action running in this job or other jobs in the same PR"
    require: false
  initialize:
    description: "Whether this action should initialize the comment to report results. Useful if multiple jobs are sharing the same comment. Pass in 'true' if this job should always create the comment"
    require: false
  summarize:
    description: "Specify whether to summarize (true), don't summarize any measurements (false), or which measurements to summarize (list of measurement names)"
    require: false
    default: "true"
  default-open:
    description: "Whether to open this action's results table by default"
    required: false
    default: "false"
  # keep-old-results:
  #   description: Whether to keep old results in the comment on re-runs
  #   required: false
  #   default: "false"
  pr-bench-name:
    description: "The name of the benchmark/version in tachometer results (i.e. benchmark.name or benchmark.version) that represents the code produced by this PR"
    required: false
  base-bench-name:
    description: "The name of the benchmark/version in tachometer results (i.e. benchmark.name or benchmark.version) that this PR should be compared to"
    required: false
  github-token:
    description: "The GITHUB_TOKEN for the current workflow run"
    required: false
    default: ${{github.token}}
  follow-symbolic-links:
    description: "Indicates whether to follow symbolic links"
    default: true
runs:
  using: "node12"
  pre: "dist/pre.js"
  main: "dist/main.js"
