name: PR Multi-Measurement Summarize Job Flow

on:
  pull_request:
    branches:
      - "**"

# The results in these jobs contain multiple measures and some jobs have a
# custom summarize parameter

jobs:
  setup:
    name: Setup Tachometer Reporting
    runs-on: ubuntu-latest
    steps:
      - name: Initialize tachometer comment
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          initialize: true

  bench_1:
    name: First Bench Job
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/multi-measure-results.json
          report-id: multi-bench-1
          pr-bench-name: local-framework
          base-bench-name: base-framework
          summarize: duration

  bench_2:
    name: Second Bench Job
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report Other Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/multi-measure-names.json
          report-id: multi-measure-names
          pr-bench-name: this-change
          base-bench-name: tip-of-tree
          summarize: render, update
