name: Pull Request Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
        env:
          TACH_REPORTER_SKIP_SNAPSHOT_TESTS: "true"
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@comment-locking
        with:
          path: tests/results/test-results.json
          report-id: test-results
          pr-bench-name: local-framework
          base-bench-name: base-framework
      # - name: Report Other Tachometer Result
      #   uses: ./
      #   with:
      #     path: tests/results/other-results.json
