name: Workflow Run Event Example

on:
  workflow_run:
    workflows: ["PR Single Job"]
    branches: ["**"]
    types:
      - completed
      - requested

# Just testing to see what happens...
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
      - run: git show HEAD
      - name: Log GitHub Context
        run: node -e 'var github = require("@actions/github"); var context = github.context; console.log("context.issue =", JSON.stringify(context.issue, null, 2)); console.log("context.repo =", JSON.stringify(context.repo, null, 2)); console.log("context = ", JSON.stringify(context, null, 2));'
